import Head from 'next/head'

export default function Home() {
  return (
    <div className="bg-black">
      <Head>
        <title>Colter Purcell</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex p-3 justify-between mix-blend-difference w-screen fixed">
        <a className="text-stone-50 text-5xl font-sans font-medium">c.</a>
        <div className="flex justify-between border border-stone-50 rounded-full">
          <a className="text-stone-50 text-xl hover:bg-stone-50 hover:text-black rounded-full py-2 px-4 transition-all duration-300">
            Home
          </a>
          <a className="text-stone-50 text-xl hover:bg-stone-50 hover:text-black rounded-full py-2 px-4 transition-all duration-300">
            About
          </a>
          <a className="text-stone-50 text-xl hover:bg-stone-50 hover:text-black rounded-full py-2 px-4 transition-all duration-300">
            Contact
          </a>
          <a className="text-stone-50 text-xl hover:bg-stone-50 hover:text-black rounded-full py-2 px-4 transition-all duration-300">
            Work
          </a>
        </div>
      </nav>
      <div className="flex flex-col justify-center h-screen w-screen">
        <div className="flex flex-col justify-center items-center mix-blend-difference">
          <h2 className="text-7xl font-semibold font-sans text-stone-50 mb-4">
            the whole package
          </h2>
          <p className="text-2xl font-normal font-sans text-stone-50 mb-4">
            Here from start to finish, front to back.
          </p>
          <button className="text-2xl font-normal font-sans text-stone-50 border border-stone-50 rounded-full p-1 px-4 hover:bg-stone-50 hover:text-black transition-all duration-200">
            <span className="hover:mx-2 transition-all">See More</span> →
          </button>
        </div>
      </div>
    </div>
  )
}
